---
stages:
  - build
  - deploy

include:

  # =========================
  # PLAYGROUND BUILD
  # =========================

  - component: gitlab.rahap.site/devops/cicd-catalog/build@main
    inputs:
      job_name: "insurehub-web-app-playground"
      job_tags:
        - shared-runner
      job_rules:
        - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"'
          when: manual
          allow_failure: false
      registry: harbor.rahap.site
      image_name: insurance/insurehub-web-app/playground
      dockerfile: Dockerfile
      dockerfile_path: .
      build_args: ""

  # =========================
  # PLAYGROUND DEPLOY
  # =========================

  - component: gitlab.rahap.site/devops/cicd-catalog/deploy@main
    inputs:
      job_name: "insurehub-web-app-playground"
      job_tags:
        - shared-runner
      job_rules:
        - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "main"'
          when: manual
          allow_failure: false
      job_needs:
        - "Build: insurehub-web-app-playground"
      registry: harbor.rahap.site
      service_image_name: insurance/insurehub-web-app/playground
      helm_release_name: insurehub-web-app
      helm_namespace: playground
      helm_values_file: values-playground.yaml
